#' Expand Bounding Box
#'
#' A function to take a bounding box (generated using st_bbox) and expand it by x meters in the X direction and y meters in the Y direction.
#'
#' @param bbox a bounding box generated by sf::st_bbox() or named numeric vector with xmin, ymin, xmax, ymax.
#' @param metresX the distance in metres that we want to expand the bounding box by in the X direction
#' @param metresY the distance in metres that we want to expand the bounding box by in the Y direction
#' @param metresX2 if specified, the meters in the Easterly direction and metresX becomes metres in the Westerly direction.
#' @param metresY2 if specified, the metres to the South. metresY becomes metres to the North.
#' @param crs_out what epsg coordinate system to return the bbox in. Defaults to lat/lng (4326).
#'
#' @return a named numeric vector of bbox extents. This can be converted into an sf object using sf::st_as_sfc(). Coordinates are in lat/lng (4326).
#'
#' @examples
#'
#' bbox <- expand_bbox(st_bbox(), 5000, 5000)
#' dbDisconnect(con)
#'
expand_bbox <- function(bbox, metresX, metresX2 = metresX,  metresY, metresY2 = metresY,
                        crs_out = 4326){
  bbox <- bbox %>%
    st_as_sfc() %>%
    sf::st_transform(crs = 4326)%>%
    st_bbox()


  bbox['xmin'] <-  bbox['xmin'] - (metresX / 6370000) * (180 / pi) / cos(bbox['xmin'] * pi/180)
  bbox['xmax'] <-  bbox['xmax'] + (metresX2 / 6370000) * (180 / pi) / cos(bbox['xmax'] * pi/180)
  bbox['ymin'] <-  bbox['ymin'] - (metresY / 6370000) * (180 / pi)
  bbox['ymax'] <- bbox['ymax'] + (metresY2 / 6370000) * (180 / pi)

  bbox %>%
    st_as_sfc() %>%
    sf::st_transform(crs = crs_out) %>%
    st_bbox()


}





